name: Upload S3

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-west-2     
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Setup
      run: npm install
        
    - name: Build
      run: npm run build

    - name: Setup Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }} 
        role-session-name: github-actions-cfg
        aws-region: us-west-2

    - name: S3 Upload
      run: aws s3 sync dist s3://$AWS_S3_BUCKET --follow-symlinks --delete

    - name: Refresh CloudFront
      run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
